 
typedef int (__stdcall*  XHCmcc_Initial)(int cardno);
typedef int (__stdcall*  Get_Lib_Version)(int cardno);
typedef int (__stdcall*  Set_Pulse_Mode)(int cardno,int value);
typedef int (__stdcall*  Set_Acc)(int cardno,int axis,double value);
typedef int (__stdcall*  Set_StartV)(int cardno,int axis,long value);
typedef int (__stdcall*  Set_MoveSpeed)(int cardno,int axis,double value);
typedef int (__stdcall*  PMove)(int cardno,int axis,int pulse);
typedef int (__stdcall*   StopPMove) (int cardno,int axis);
typedef int (__stdcall*  Sudden_Stop)(int cardno,int axis);
typedef int (__stdcall*   SignalMove)(int cardno,int axis,int Signalio,int lmtpulse,int aftermove,int LmtEn);
typedef int (__stdcall*   Set_Command_Pos)(int cardno,int axis,int abspos);
typedef int (__stdcall*   Get_Command_Pos)(int cardno,int axis,int *pos);
typedef int (__stdcall*   Get_Status)(int cardno,int axis,int *value);
typedef int (__stdcall*   Start_FifoMove)(int cardno);//auto fill and run;
typedef int (__stdcall*   Stop_FifoMove)(int cardno);
typedef int (__stdcall*   Write_Bit)(int cardno,int number,int value);
typedef int (__stdcall*   Get_CodeLine)(int cardno);
typedef int (__stdcall*    Read_Bit)(int cardno,int number);
typedef int (__stdcall*   Set_IoIn_Mode)(int cardno, int ioin, int mode, int logic,int Enalbe);
typedef int (__stdcall*   UnlimtSignal)(int cardnum,int signalnum);
typedef int (__stdcall*   Set_Spindle_Speed) (int cardno,int maxspeed, int currentspeed,int mode);
typedef int (__stdcall*   Fifo_InP_Command)(int cardno,int ComNum,int Para0,int Para1,int Para2,int Para3,int Para4,int Para5,int Para6);
typedef int (__stdcall*   Read_Fifo_State)(int cardno,int *buflength,int* emptylength);
typedef int (__stdcall*   Reset_Fifo)(int cardno);
typedef int (__stdcall*   StopPlug)(int cardno);
typedef int (__stdcall*   SetSoftLmt)(int cardno,int axis,int  absposplus,int  absposminus);
typedef int (__stdcall*  OpenMotoionDevcie)(int cardno );
typedef int (__stdcall*   CloseMotoionDevcie)(int cardno );
typedef int (__stdcall*  Set_Stepper)(int cardno,int axis,double value);
typedef int (__stdcall*   Set_SoftLmtEnalbe)(int cardno,int enalbe);
typedef int (__stdcall*   CloseSpindle)(int cardno);
typedef int (__stdcall*  OpenSpindle)(int cardno,int fwd);
typedef int (__stdcall*   Set_MotorDirLevel)(int cardno,int axis,int Level);
typedef int (__stdcall*  Set_MotorPulsLevel)(int cardno,int axis,int Level);
typedef int (__stdcall*   Set_SpindPulsPerRotate)(int cardno,int sPulsPerRotate);
 
 XHCmcc_Initial    XHCmcc_Initia;
 Get_Lib_Version   Get_Lib_Versio;
 Set_Pulse_Mode    Set_Pulse_Mod ;
 Set_Acc           Set_Ac ;
 Set_StartV         Set_Start;
 Set_MoveSpeed      Set_MoveSpee;
 PMove              PMov    ;     
 StopPMove          StopPMov;
  Sudden_Stop       Sudden_Sto;
 SignalMove         SignalMov;
 Set_Command_Pos        Set_Command_Po; 
 Get_Command_Pos    Get_Command_Po;
 Get_Status          Get_Statu;
 Start_FifoMove      Start_FifoMov;
 Stop_FifoMove       Stop_FifoMov; 
 Write_Bit           Write_Bi; 
 Get_CodeLine        Get_CodeLin;
 Read_Bit             Read_Bi;
 Set_IoIn_Mode        Set_IoIn_Mod;
 UnlimtSignal        UnlimtSigna  ;
 Set_Spindle_Speed   Set_Spindle_Spee;
 Fifo_InP_Command     Fifo_InP_Comman; 
  Read_Fifo_State     Read_Fifo_Stat;
 Reset_Fifo           Reset_Fif;
 StopPlug             StopPlu;
 SetSoftLmt           SetSoftLm; 
 OpenMotoionDevcie     OpenMotoionDevci;
  CloseMotoionDevcie   CloseMotoionDevci ;
 Set_Stepper           Set_Steppe; 
 Set_SoftLmtEnalbe     Set_SoftLmtEnalb;
 CloseSpindle          CloseSpindl;
 OpenSpindle            OpenSpindl ;
 Set_MotorDirLevel     Set_MotorDirLeve;
 Set_MotorPulsLevel     Set_MotorPulsLeve;
 Set_SpindPulsPerRotate  Set_SpindPulsPerRotat;